<?php
include_once('../header.php');
?>
<h2 class="page_title">Known Bugs</h2>
<br>
<div class="bugs">
    <p>
        Here is a list of currently known/active bugs with gameplay impact in Hearthstone Battlegrounds:
    </p>
    <ul>
        <li>Trinkets which mention a minion type will sometimes display minion types not in the game (like Draenai or Night Elves). This is only a visual bug.</li>
        <li><a class="hoverimage" href="/bgstrategy/spell/?id=30">Planar Telescope</a> gives nothing if your most common type is not one of the minion types in the game, and you're not at Tier 6 (where there is an "All" type minion).</li>
    </ul>
    <ul>
        <li>Duos: Your partner's gold amount is not shown.</li>
        <li>Duos: There is a chance that after hiding your discover options and switching to your partner's screen, you won't be able to your options again.</li>
        <li>Duos: Treasures from <a class="hoverimage" href="/bgstrategy/hero/?id=71">Tickatus</a>'s hero power can't be passed to your teammate.</li>
        <li>Duos: The quest indicator for the hero power of <a class="hoverimage" href="/bgstrategy/hero/?id=87">Sire Denathrius</a> will be hidden on your screen, making it harder to track your quest progress (your teammate can see it though).</li>
    </ul>
    <ul>
        <li>
            <del>Giving a Magnetic mech in the shop Taunt, and then Magnetizing it, the Taunt won't apply to <a class="hoverimage" href="/bgstrategy/minion/?id=353">Polarizing Beatboxer</a>. Also, temporary stat buffs on Magnetic minions will no longer be applied to the Beatboxer, too (might be intended).</del>
            (fixed in 30.4.1.)
        </li>

        <li>
            <del>When tripling an "All" type minion with <a class="hoverimage" href="/bgstrategy/minion/?id=356">Elemental of Surprise</a>, the Golden version loses its "All" type and becomes just an elemental.</del>
            (fixed in 30.2.1)
        </li>
        <li>
            <del>The trinket <a class="hoverimage" href="/bgstrategy/trinket/?id=45">Colorful Compass</a> can offer a version for a minion type not in the game if it's your most common type (because of "All" minions).</del>
            (fixed in 30.2.1)
        </li>
        <li>
            <del>The trinket <a class="hoverimage" href="/bgstrategy/trinket/?id=37">Twin Sky Lanterns</a> doesn't work the first turn you have it.</del>
            (fixed in 30.2.1)
        </li>
        <li>
            <del>Some deathrattle effects (like <a class="hoverimage" href="/bgstrategy/minion/?id=208">Leeroy</a>) will not be transfered to the Fish of <a class="hoverimage" href="/bgstrategy/hero/?id=45">N'Zoth</a>.</del>
            (fixed in 30.2.0)
        </li>
        <li>
            <del>All abilites on golden Zilliax modules (like <a class="hoverimage" href="/bgstrategy/minion/?id=475">Whirring</a> or <a class="hoverimage" href="/bgstrategy/minion/?id=507">Bonding</a>), when generated by other means than trippling, will not work.</del>
            (fixed in 30.2.0)
        </li>
        <li>
            <del>When you have multiple <a class="hoverimage" href="/bgstrategy/minion/?id=475">Timecap'n Hooktail</a> on your board, minions with buff effects triggered by it (like <a class="hoverimage" href="/bgstrategy/minion/?id=42">Whelp Smuggler</a> or <a class="hoverimage" href="/bgstrategy/minion/?id=535">Defiant Shipwright</a>) will not proc for each instance, but only once.</del>
            (fixed in 30.0.0)
        </li>
        <li>
            <del><a class="hoverimage" href="/bgstrategy/minion/?id=507">Zilliax: Bonding Module</a> that is goldenized in the shop can't be Magnetized.</del>
            (fixed in 29.6.1)
        </li>
        <li>
            <del><a class="hoverimage" href="/bgstrategy/minion/?id=542">Fairy Gillmother</a> can generate herself.</del>
            (fixed in 29.6.1)
        </li>
        <li>
            <del>Rat Pack and Lil’ Rag were not added to the minion pool with Patch 29.4.2 as intended.</del>
            (fixed in 29.4.3)
        </li>
        <li>
            <del>When trippling <a class="hoverimage" href="/bgstrategy/minion/?id=470">Winged Chimera</a> with <a class="hoverimage" href="/bgstrategy/minion/?id=356">Elemental of Surprise</a> its ability counter will be set to 0, and it will lose its ability to buff your minions, permanently.</del>
            (fixed in 29.4.1)
        </li>
    </ul>
    <br><br>
    <p>
        <span class="small_info">Last update: 15.09.2024</span>
    </p>
</div>

<?php
include_once('../footer.php');
?>

