<?php
include_once('../header.php');
?>
<h2 class="page_title">Known Bugs</h2>
<br>
<div class="bugs">
    <p>
        Here is a list of currently known/active bugs with gameplay impact in Hearthstone Battlegrounds:
    </p>
    <ul>
        <li>When you have multiple <a class="hoverimage" href="/bgstrategy/minion/?id=475">Timecap'n Hooktail</a> on your board, minions with buff effects triggered by it (like <a class="hoverimage" href="/bgstrategy/minion/?id=42">Whelp Smuggler</a> or <a class="hoverimage" href="/bgstrategy/minion/?id=535">Defiant Shipwright</a>) will not proc for each instance, but only once.</li>
        <li>All abilites on Zilliax modules (like <a class="hoverimage" href="/bgstrategy/minion/?id=475">Whirring</a>), when generated by the hero power of <a class="hoverimage" href="/bgstrategy/hero/?id=9">Captain Eudora</a> will not work.</li>
        <li>Duos: The hero power of <a class="hoverimage" href="/bgstrategy/hero/?id=64">Tamsin Roame</a> has a chance to consume two minions instead of one.</li>
        <li>
            <del>When trippling <a class="hoverimage" href="/bgstrategy/minion/?id=470">Winged Chimera</a> with <a class="hoverimage" href="/bgstrategy/minion/?id=356">Elemental of Surprise</a> its ability counter will be set to 0 and it will lose its ability to buff your minions, permanently.</del>
            (fixed in 29.4.1)
        </li>
    </ul>
    <br><br>
    <p>
        <span class="small_info">Last update: 12.05.2024</span>
    </p>
</div>

<?php
include_once('../footer.php');
?>

